events {}

http {
  server {
    listen 80;

    location /api/ {
      proxy_pass http://floci-eks-lomax-cluster:30080/;
      proxy_set_header Host $host;
      client_max_body_size 6M;
      proxy_connect_timeout 180s;
      proxy_send_timeout 180s;
      proxy_read_timeout 180s;
    }

    location / {
      proxy_pass http://floci-eks-lomax-cluster:30081/;
      proxy_set_header Host $host;
    }
  }
}